config/routes.rb
Rails.application.routes.draw do
  resources :lists do 
    resources :todos
  end

  devise_for :users
    resources :users, only: [:update]

  get 'welcome/index'
  
  root to: 'welcome#index'
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :todos
  belongs_to :user

  scope :visible_to, -> (user) { user ? all : where(public: true) }
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :list
  belongs_to :user

  def time_left
    days_ago_created = ((Time.now - self.created_at)/84600).round
    time_left = 7 - days_ago_created
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_one :list, dependent: :destroy
  has_many :todos, dependent: :destroy

	def has_list?
		list = self.list
		list != nil
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
   
   before_action :configure_permitted_parameters, if: :devise_controller?
 
   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
   end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  
def new
    @list = List.new
  end

  def create
    #associate the new list with a user
    @list = List.new(user_id: current_user.id)
    if @list.save
      flash[:notice] = "Your to do list was created."
      redirect_to @list
    else
      flash[:error] = "There was an error creating your list. Please try again."
      render :new
    end
  end

  def show
    # show current user's list
    #Render a form that will collect useful params to create a new Todo (GET)
    @user = current_user
    @list = List.find(params[:id])
    @todo = Todo.new
    @todos = @list.todos
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  respond_to :html, :js

  def new#Render a form that will collect useful params (GET)
    @todo = Todo.new
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params.require(:todo).permit(:description, :time_left, :complete))
    if @todo.save
      flash[:notice] = "Your to do was added."
      redirect_to @list
    else
      flash[:error] = "There was an error creating your to do. Please try again."
      render :new
    end
  end

  def create
  #Sole responsibility is to store params as a Todo into the database (POST)

    @list = List.find(params[:list_id])
    @todo = Todo.new(params.require(:todo).permit(:description, :time_left, :complete))
    @todo.list = @list

    if @todo.save
      flash[:notice] = "Your to do was added."
      redirect_to @todo.list
    else
      flash[:error] = "There was an error creating your to do. Please try again."
      render :new
    end
  end

  def destroy
    #you have params: list_id and id
     @list = List.find(params[:list_id])
     @todo = Todo.find(params[:id])
 
     if @todo.destroy
       flash[:notice] = "\"#{@todo.description}\" was deleted successfully."
     else
       flash[:error] = "There was an error deleting the to do."
     end

     respond_with(@todo) do |format|
       format.html { redirect_to @todo.list }
     end
  end

end

app/controllers/users_controller.rb
 class UsersController < ApplicationController
   before_action :authenticate_user!
 
   def update
     if current_user.update_attributes(user_params)
       flash[:notice] = "User information updated"
       redirect_to edit_user_registration_path
     else
       flash[:error] = "Invalid user information"
       redirect_to edit_user_registration_path
     end
   end
 
   private
 
   def user_params
     params.require(:user).permit(:name)
   end
 end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", welcome_index_path %></li>
        <% if current_user && current_user.has_list? %>
             <li><%= link_to "My To Do List", list_path(current_user.list)  %></li>
         <% end %>  
         <div class="pull-right user-info">
           <% if current_user %>
             Hello <%= link_to (current_user.name || current_user.email), edit_user_registration_path %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
           <% else %>
             <%= link_to "Sign In", new_user_session_path %> or 
             <%= link_to "Sign Up", new_user_registration_path %>
           <% end %>
         
         </div>
    </ul>
      <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:error] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:error] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>
       
    <%= yield %>
  </div>

</body>
</html>

app/views/lists/new.html.erb
<h1>Create a To Do List</h1>
<p>Would you like to create a new to do list?</p>

<%= form_for List.new do |f| %>
  <div class="form-group">
    <%= f.submit "Create List", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/lists/show.html.erb
<div class ='row'>
  <h1><%= @user.name %>'s To Do List</h1>
</div>

<!-- Render partial for Form to add a ToDo -->
<%= render partial: 'todos/form', locals: { list: @list, todo: @todo } %>

<div class ='row'>
  <h4><div class='row header'>
    <div class='col-md-6'>To Do</div>
    <div class='col-md-2'>Time Left</div>
    <div class='col-md-2'>Completed?</div>
  </div></h4>
</div>

<!-- List of todos already entered -->
<%= render partial: 'todos/todo', collection: @todos %>


<script>
  $(".make-delete").click(function(){

    list_id = $(this).data("list-id")
    id = $(this).data("id")
    $.ajax("/lists/"+list_id+"/todos/"+id+".js", {method: "DELETE"})
  })
</script>

app/views/todos/_form.html.erb
 <%= form_for [list, todo] do |f| %>
   <div class='row'>
    <div class='col-md-8'>
      <%= f.label 'Add your to-do:' %>
      <%= f.text_field :description %>
    </div>
  </div>
 
   <%= f.submit "Save", class: 'btn btn-success' %>
 <% end %>

app/views/todos/_todo.html.erb
<div id= "fubar<%= todo.id %>">
  <div class='col-md-6'>
    <%= todo.description %>
  </div>

  <div class='col-md-2', align='left'>
    <%= todo.time_left %> days
  </div>

  <!-- If todo is checked, then remove -->
  <div class='col-md-2', align='center'>
    <%= check_box(todo, :complete, checked_value: "1", unchecked_value: "0", class: "make-delete", :"data-list-id" => todo.list.id, :"data-id" => todo.id) %>
  </div>
</div>

app/views/todos/destroy.js.erb
<% if @todo.destroyed? %>
  $('#fubar' +<%= @todo.id %>).hide();
<% else %>
  $('#fubar' +<%= @todo.id %>).prepend("<div class='alert alert-error'><%= flash[:error] %></div>");
<% end %>

app/views/welcome/index.html.erb
<br/>
<div>
<p class="lead"> 
	Create a to-do list. Mark your items off as complete, or they self-destruct after seven days.
</p>
<% if current_user %>
	<p><%= link_to "Create a self-destructing to-do list!", new_list_path unless current_user.has_list? %></p>
<% end %>
<%= image_tag 'beachwtext.jpg' %> 
</div>